intro/urls.py
from django.urls import path
from . import views

app_name='intro'
urlpatterns = [
    path('', views.profile, name="profile"),
]

posts/urls.py
from django.urls import path
from .views import new, create, main, show, update, delete #, rev, new_review

app_name="posts"
urlpatterns = [
    path('new/', new, name="new"),
    path('create/', create, name="create"),
    path('', main, name="main"),
    path('show/<int:id>',show, name="show"),
    path('update/<int:id>',update, name="update"),
    path('delete/<int:id>', delete, name="delete"),
    #path('rev/', rev, name="rev"),
    #path('new_review/',new_review,name="new_review"),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('intro/', include('intro.urls')),
    path('', views.main, name="main"),
    path('posts/', include('posts.urls')),
    path('accounts/', include('allauth.urls')),
] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

intro/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Product (models.Model):
    title=models.CharField(max_length=50, null=False)
    content=models.TextField()
    price=models.IntegerField(default=0)
    inventory=models.IntegerField(default=0)
    view_count=models.IntegerField(default=0)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)
    image=models.ImageField(upload_to='images/', null=True)
    user=models.ForeignKey(User, on_delete=models.CASCADE, null=True)

class Review(models.Model):
    content=models.TextField()
    grade=models.IntegerField(default=0)
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    product=models.ForeignKey(Product, on_delete=models.CASCADE, related_name='reviews')
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

intro/views.py
from django.shortcuts import render

# Create your views here.
def profile(request):
    return render(request, 'intro/profile.html')

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Product, Review

# Create your views here.

def main(request):
    posts=Product.objects.all()
    return render(request, 'posts/main.html', {'posts':posts})

def new(request):
    return render(request, 'posts/new.html')

def create(request):
    if request.method == "POST":
        title = request.POST.get('title')
        content = request.POST.get('content')
        price = request.POST.get('price')
        inventory=request.POST.get('inventory')
        image=request.FILES.get('image')
        user=request.user
        Product.objects.create(title=title, content=content, image=image, user=user, price=price, inventory=inventory)
        return redirect('main')

def show(request,id):
    post=Product.objects.get(pk=id)
    post.view_count += 1
    post.save()
#    reviews = Review.objects.all()
    return render(request, 'posts/show.html', {'post': post}) #, 'reviews':reviews})

def update(request, id):
    post=get_object_or_404(Product, pk=id)
    if request.method=="POST":
            post.title=request.POST['title']
            post.content=request.POST['content']
            post.price=request.POST['price']
            post.inventory=request.POST['inventory']
            post.image=request.FILES.get('image')
            post.save()
            return redirect('posts:show', post.id)
    return render(request, 'posts/update.html', {'post' : post})

def delete(request, id):
    post=get_object_or_404(Product, pk=id)
    post.delete()
    return redirect("posts:main")
'''
def new_review(request):
    return render(request, 'posts/rev.html')

def rev(request):
    if request.method == 'POST':
        user = request.POST.get('user')
        content = request.POST.get('content')
        Review.objects.create(user = user, content = content)
    return redirect('main')

'''

shop/views.py
from django.shortcuts import render

def main(request):
    return render(request, 'main.html')

intro/templates/intro/profile.html
{% extends 'base.html' %}
<h1>쇼핑몰 안내</h1>

posts/templates/posts/main.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h1>상품 목록입니다.</h1>
    <div class="row">
        {% for post in posts %}
            <div class="col-md-4 col-12">
                <div class="card" style="width: 18rem; margin-top: 20px;">
                    <div class="card-bodpyy">
                        <h5 class="card-title">상품명 : {{ post.title }}</h5>
                        <p>조회수 : {{ post.view_count }}</p>
                        {% if post.image %}
                            <img src="{{ post.image.url }}">
                        {% endif %}
                        <p class="card-text">가격 : {{ post.price }} 원</p>
                        <p>재고 : {{ post.inventory }} 개</p>
                        <a href="{% url 'posts:show' post.pk %}" class="btn btn-outline-secondary">상세보기</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <br>
    <a href="{% url 'posts:new' %}" class="btn btn-outline-success">새 상품 올리기</a>
</div>
{% endblock %}

posts/templates/posts/new.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h1>
        새 상품 올리기
    </h1>
    <form action="{% url 'posts:create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label>상품명</label>
            <input type="text" class="form-control" name="title">
        </div>
        <div class="form-group">
            <label>가격</label>
            <input type="text" class="form-control" name="price">
        </div>
        <div class="form-group">
            <label>재고</label>
            <textarea class="form-control" name="inventory"></textarea>
        </div>
        <div class="form-group">
            <label>상품 설명</label>
            <input type="text" class="form-control" name="content">
        </div>
        <input type="file", name="image">
        <input type="submit" value="글 작성" class="btn btn-outline-primary">
    </form>
    </div>
{% endblock %}

posts/templates/posts/rev.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h1>
        리뷰 작성
    </h1>
    <form action="{% url 'posts:rev' %}" method="POST2">
        {% csrf_token %}
        <div class="form-group">
            <label>상품명</label>
            <input type="text" class="form-control" name="product">
        </div>
        <div class="form-group">
            <label>평점</label>
            <input type="text" class="form-control" name="grade">
        </div>
        <div class="form-group">
            <label>내용</label>
            <textarea class="form-control" name="content"></textarea>
        </div>
        <input type="submit" value="리뷰 작성" class="btn btn-outline-primary">
    </form>
    </div>
{% endblock %}

posts/templates/posts/rev_update.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h1>
        리뷰 수정하기
    </h1>
    <form action="{% url 'posts:rev_update' post.id %}" method="POST2">
        {% csrf_token %}
        <div class="form-group">
            <label>상품명</label>
            <input type="text" class="form-control" name="product" value="{% review.product %}">
        </div>
        <div class="form-group">
            <label>평점</label>
            <input type="text" class="form-control" name="grade" value="{% review.grade %}">
        </div>
        <div class="form-group">
            <label>내용</label>
            <textarea class="form-control" name="content" value="{% review.content %}"></textarea>
        </div>
        <input type="submit" value="리뷰 수정" class="btn btn-outline-primary">
    </form>
    </div>
{% endblock %}

posts/templates/posts/show.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h2>상품 상세보기</h2><br>
    <p>조회수 : {{ post.view_count }}</p>
    {% if post.user %}
        <h3>작성자 : {{ post.user }}</h3><br>
    {% else %}
        <h3>작성자 : 알 수 없음 </h3><br>
    {% endif %}
    <h3>상품명 : {{ post.title }} </h3><br>
    <h3>가격 : {{ post.price }} 원</h3><br>
    <h3>재고 : {{ post.inventory }} 개</h3><br>
    <h3>상품 설명 : {{ post.content }} </h3><br>
    <h3>작성 시각 : {{ post.created_at }} </h3><br>
    <h3>수정 시각 : {{ post.updated_at }} </h3><br>
    
    {% if post.image %}
        <img src="{{ post.image.url }}">
    {% endif %}
    {% if user == post.user %}
        <br>
        <br>
        <a href="{% url 'posts:update' post.pk%}" class="btn btn-primary">수정하기</a>
        <a href="{% url 'posts:delete' post.pk%}" class="btn btn-primary">삭제하기</a>
    {% endif %}
    <br>
    <br>
</div>
{% endblock %}

posts/templates/posts/update.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h1>
        상품 정보 수정하기
    </h1>
    <form action="{% url 'posts:update' post.id %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label>상품명</label>
            <input type="text" class="form-control" name="title" value="{{ post.title }}">
        </div>
        <div class="form-group">
            <label>가격</label>
            <input type="text" class="form-control" name="price" value="{{ post.price }}">
        </div>
        <div class="form-group">
            <label>재고</label>
            <input type="text" class="form-control" name="inventory" value="{{ post.inventory }}"></textarea>
        </div>
        <div class="form-group">
            <label>상품 설명</label>
            <input type="text" class="form-control" name="content" value="{{ post.content }}">
        </div>
        <input type="file" name="image" value="{{ post.image }}">
        <input type="submit" value="글 수정" class="btn btn-outline-primary">
    </form>
    </div>
{% endblock %}

shop/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/css/bootstrap.min.css" integrity="sha384-VCmXjywReHh4PwowAiWNagnWcLhlEJLA5buUprzK8rxFgeH0kww/aWY76TfkUoSX" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/project.css' %}">
    
    <title>shop</title>
  </head>
  <body>
    {% include 'shared/_navbar.html' %}
    
    {% block content %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/js/bootstrap.min.js" integrity="sha384-XEerZL0cuoUbHE4nZReLT7nx9gQrQreJekYhJD9WNWhH8nEW+0c5qq7aIo2Wl30J" crossorigin="anonymous"></script>
  </body>
</html>

shop/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container">
    <h1>쇼핑몰에 오신 걸 환영합니다</h1>
    <img src="{% static 'img/banner.jpg' %}">
{% if user.is_authenticated %}
    <br>
    <h1>어서오세요.</h1>
{% else %}
    <br><br>
    <h3>로그인 후 이용이 가능합니다.</h3>
    <a href="{% url 'account_login' %}" class="btn btn-primary">로그인</a>
    <a href="{% url 'account_signup' %}" class="btn btn-warning">회원가입</a>
{% endif %}
</div>
{% endblock %}

shop/templates/shared/_navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'main' %}">Shop</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'main' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'posts:main' %}">상품목록</a>
        </li>
      </ul>
    </div>

    <ul class="nav navbar-nav navbar-right">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Account</a>
        <div class="dropdown-menu">
          {% if user.is_authenticated %}
            <a class="dropdown-item" href="{% url 'account_logout' %}" class="nav-link">Logout</a>
            <a class="dropdown-item" href="{% url 'account_change_password' %}">Change PW</a>
          {% else %}
            <a class="dropdown-item" href="{% url 'account_login' %}" class="nav-link">Login</a>
            <a class="dropdown-item" href="{% url 'account_signup' %}" class="nav-link">Sign Up</a>
          {% endif %}
        </div>
      </li>
    </ul>
  </nav>